name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uniunt/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bookapp-deployed-by-actions" #Must be unique in Heroku
          heroku_email: "uniunt@gmail.com"
          appdir: "backend" # <- This will point to the api folder in your project
          procfile: "web:node backend/app.js"
